# NumPy Practice Notebook

This notebook follows the lecture slides and provides hands-on practice with NumPy.

## 1. Introduction
NumPy is a fundamental package for scientific computing in Python. It provides:
- Homogeneous multidimensional array objects
- Fast mathematical operations
- Broadcasting
- Linear algebra, statistics, random simulations


## 2. Arrays

### 2.1 Array Creation

In [8]:

import numpy as np

# Examples
a1 = np.array([1,2,3])
print("1D array:", a1)

a2 = np.array([[1,2,3],[4,5,6]])
print("2D array:")
print(a2)

a3 = np.zeros((2,2,2))
print("3D array of zeros:")
print(a3)

1D array: [1 2 3]
2D array:
[[1 2 3]
 [4 5 6]]
3D array of zeros:
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


**Exercise 1:** Create a 1D array with values from 10 to 50 (inclusive).

In [ ]:
# Your answer here
your_array = ...

In [ ]:

# ✅ Test
assert np.array_equal(your_array, np.arange(10, 51)), "❌ Not correct, try again!"
print("✅ Correct!")



<details>
<summary>✅ Show Solution</summary>

```python
your_array = np.arange(10, 51)
```
</details>


### 2.2 Selecting Array Entries

In [ ]:

arr = np.arange(1, 11)
print("Array:", arr)
print("First element:", arr[0])
print("Last 3 elements:", arr[-3:])
print("Every second element:", arr[::2])


**Exercise 2:** From the array `np.arange(1,21)`, extract every 3rd element.

In [ ]:
# Your answer here
result = ...

In [ ]:

# ✅ Test
expected = np.arange(1,21)[::3]
assert np.array_equal(result, expected), "❌ Not correct, try again!"
print("✅ Correct!")



<details>
<summary>✅ Show Solution</summary>

```python
result = np.arange(1,21)[::3]
```
</details>


### 2.3 NumPy Arrays vs Python Lists

In [ ]:

import time

lst = list(range(1,1000000))
arr = np.arange(1,1000000)

# Squaring list (slow)
start = time.time()
lst2 = [x**2 for x in lst]
print("List time:", time.time()-start)

# Squaring array (fast)
start = time.time()
arr2 = arr**2
print("Array time:", time.time()-start)


### 2.4 Data Types and Attributes

In [ ]:

arr = np.array([1,2,3], dtype=np.float32)
print("Array:", arr)
print("Data type:", arr.dtype)
print("Shape:", arr.shape)
print("Size:", arr.size)


**Exercise 3:** Create a 3x3 matrix of ones with integer type.

In [ ]:
# Your answer here
matrix = ...

In [ ]:

# ✅ Test
expected = np.ones((3,3), dtype=int)
assert np.array_equal(matrix, expected), "❌ Not correct, try again!"
print("✅ Correct!")



<details>
<summary>✅ Show Solution</summary>

```python
matrix = np.ones((3,3), dtype=int)
```
</details>


## 3. Operations on Arrays

### 3.1 Basic Array Operations

In [ ]:

x = np.array([1,2,3])
y = np.array([4,5,6])

print("x + y:", x+y)
print("x * y:", x*y)
print("x ** 2:", x**2)


**Exercise 4:** Create arrays `[10,20,30]` and `[1,2,3]`. Compute their product.

In [ ]:
# Your answer here
prod = ...

In [ ]:

# ✅ Test
a = np.array([10,20,30])
b = np.array([1,2,3])
expected = a*b
assert np.array_equal(prod, expected), "❌ Not correct, try again!"
print("✅ Correct!")



<details>
<summary>✅ Show Solution</summary>

```python
a = np.array([10,20,30])
b = np.array([1,2,3])
prod = a * b
```
</details>


### 3.2 Broadcasting

In [ ]:

M = np.ones((3,3))
v = np.array([1,2,3])

print("Matrix:
", M)
print("Vector:", v)
print("M + v:
", M+v)


**Exercise 5:** Create a 5x5 matrix of ones and add `[0,1,2,3,4]` to each row using broadcasting.

In [ ]:
# Your answer here
result = ...

In [ ]:

# ✅ Test
M = np.ones((5,5))
v = np.arange(5)
expected = M + v
assert np.array_equal(result, expected), "❌ Not correct, try again!"
print("✅ Correct!")



<details>
<summary>✅ Show Solution</summary>

```python
M = np.ones((5,5))
v = np.arange(5)
result = M + v
```
</details>


### 3.3 Useful Operations

In [ ]:

arr = np.random.randint(1,100,(3,3))
print("Array:
", arr)
print("Max:", arr.max())
print("Mean:", arr.mean())
print("Sum:", arr.sum())
print("Transpose:
", arr.T)


**Exercise 6:** Generate a 4x4 matrix of random integers (0–9). Compute the column sums.

In [ ]:
# Your answer here
col_sums = ...

In [ ]:

# ✅ Test
test_arr = np.random.randint(0,10,(4,4))
# regenerate consistently for test
np.random.seed(0)
matrix = np.random.randint(0,10,(4,4))
expected = np.sum(matrix, axis=0)
assert col_sums.shape == expected.shape, "❌ Shape is wrong"
print("✅ Looks good (values vary each run)")



<details>
<summary>✅ Show Solution</summary>

```python
matrix = np.random.randint(0,10,(4,4))
col_sums = np.sum(matrix, axis=0)
```
</details>


## 4. Resources
- [NumPy Documentation](https://numpy.org/doc/stable/)
- [W3Schools NumPy Tutorial](https://www.w3schools.com/python/numpy/default.asp)
- [SciPy Lectures](https://scipy-lectures.org/)